spring :
  datasource :
    #[시작] mysql
    url: ★
    username : ★
    password : ★
    driver-class-name : org.mariadb.jdbc.Driver
    #[종료] mysql

    #[시작] hikari
    type: com.zaxxer.hikari.HikariDataSource
    connection-timeout: 30000
    max-lifetime: 300000
    maximum-pool-size: 5
    hikari:
      connectionTimeout : 30000
      maximumPoolSize : 10
      maxLifetime : 1800000
      poolName : HikariCP
      readOnly : false
      connectionTestQuery : SELECT 1
    #[종료] hikari

  devtools:
    restart:
      enabled: false

  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database : myboard
      username : admin
      #password :

logging:
  config: classpath:log4j2-local.yml